#!/bin/bash

# SocioImpact ERP - Quick Command Reference
# Copy and paste commands as needed for development and deployment

echo "🚀 SocioImpact ERP - Command Reference"
echo "========================================"
echo ""

# ============ DEVELOPMENT ============
echo "📝 DEVELOPMENT COMMANDS"
echo ""
echo "Start development servers (Laravel + Vite):"
echo "  composer run dev"
echo ""
echo "View logs in real-time:"
echo "  composer run logs"
echo ""
echo "Start queue worker (for emails):"
echo "  php artisan queue:work"
echo ""
echo "Interactive shell:"
echo "  php artisan tinker"
echo ""

# ============ DATABASE ============
echo "🗄️  DATABASE COMMANDS"
echo ""
echo "Run migrations:"
echo "  php artisan migrate"
echo ""
echo "Fresh migration + seed (DESTRUCTIVE):"
echo "  php artisan migrate:fresh --seed"
echo ""
echo "Seed database with test data:"
echo "  php artisan db:seed"
echo ""
echo "Rollback last migration:"
echo "  php artisan migrate:rollback"
echo ""

# ============ CODE GENERATION ============
echo "🛠️  CODE GENERATION"
echo ""
echo "Make new controller:"
echo "  php artisan make:controller YourController"
echo ""
echo "Make new model with migration:"
echo "  php artisan make:model YourModel -m"
echo ""
echo "Make new policy:"
echo "  php artisan make:policy YourPolicy --model=YourModel"
echo ""
echo "Make form request:"
echo "  php artisan make:request StoreYourRequest"
echo ""
echo "Make action:"
echo "  php artisan make:action YourAction"
echo ""

# ============ TESTING ============
echo "🧪 TESTING COMMANDS"
echo ""
echo "Run all tests:"
echo "  php artisan test"
echo ""
echo "Run specific test:"
echo "  php artisan test tests/Feature/ProjectTest.php"
echo ""
echo "Run tests with coverage:"
echo "  php artisan test --coverage"
echo ""

# ============ CODE QUALITY ============
echo "✨ CODE QUALITY COMMANDS"
echo ""
echo "Format code with Pint:"
echo "  vendor/bin/pint"
echo ""
echo "Format only dirty files:"
echo "  vendor/bin/pint --dirty"
echo ""
echo "Check PHP static analysis:"
echo "  vendor/bin/phpstan analyse"
echo ""
echo "Run linter:"
echo "  npx eslint resources/js"
echo ""

# ============ PERMISSIONS ============
echo "🔐 PERMISSION MANAGEMENT (Spatie)"
echo ""
echo "Show all roles:"
echo "  php artisan tinker"
echo "  >>> Role::all()"
echo ""
echo "Show all permissions:"
echo "  >>> Permission::all()"
echo ""
echo "Assign role to user:"
echo "  >>> User::find(1)->assignRole('head')"
echo ""
echo "Give user permission directly:"
echo "  >>> User::find(1)->givePermissionTo('approve reimbursements')"
echo ""
echo "Check user role:"
echo "  >>> User::find(1)->hasRole('superadmin')"
echo ""
echo "Check user permission:"
echo "  >>> User::find(1)->hasPermissionTo('create projects')"
echo ""

# ============ BUILDING ============
echo "🏗️  BUILD & DEPLOYMENT"
echo ""
echo "Build frontend for production:"
echo "  npm run build"
echo ""
echo "Build backend only:"
echo "  composer install --optimize-autoloader --no-dev"
echo ""
echo "Clear all caches:"
echo "  php artisan cache:clear"
echo "  php artisan config:cache"
echo "  php artisan route:cache"
echo "  php artisan view:cache"
echo ""
echo "Optimize autoloader:"
echo "  composer dump-autoload --optimize"
echo ""

# ============ DATABASE BACKUP ============
echo "💾 DATABASE BACKUP"
echo ""
echo "Export database:"
echo "  mysqldump -u root -p socio_impact > backup.sql"
echo ""
echo "Import database:"
echo "  mysql -u root -p socio_impact < backup.sql"
echo ""

# ============ TROUBLESHOOTING ============
echo "🐛 TROUBLESHOOTING"
echo ""
echo "Clear config cache:"
echo "  php artisan config:clear"
echo ""
echo "Regenerate app key:"
echo "  php artisan key:generate"
echo ""
echo "Fix file permissions:"
echo "  chmod -R 775 storage bootstrap/cache"
echo ""
echo "Reset database:"
echo "  php artisan migrate:reset"
echo ""
echo "Install dependencies:"
echo "  composer install && npm install"
echo ""

# ============ ROUTES ============
echo "🛣️  ROUTE COMMANDS"
echo ""
echo "List all routes:"
echo "  php artisan route:list"
echo ""
echo "List specific route:"
echo "  php artisan route:list --name=projects"
echo ""

# ============ DEBUGGING ============
echo "🔍 DEBUGGING"
echo ""
echo "Enable debug mode:"
echo "  APP_DEBUG=true in .env"
echo ""
echo "Dump variable and die:"
echo "  dd(\$variable);"
echo ""
echo "Log message:"
echo "  Log::info('message');"
echo ""
echo "View logs:"
echo "  tail -f storage/logs/laravel.log"
echo ""

echo ""
echo "========================================"
echo "For more help, check:"
echo "  - SPATIE_INTEGRATION_COMPLETE.md"
echo "  - IMPLEMENTATION_GUIDE_SPATIE.md"
echo "  - https://laravel.com/docs"
echo "  - https://spatie.be/docs/laravel-permission"
echo "========================================"
echo ""
